#!/bin/bash
# Remove unnecessary files - run: bash do_cleanup.sh

cd "$(dirname "$0")" || exit 1

files_removed=0

rm -f 00_START_HERE.md && ((files_removed++)) && echo "✓ Removed 00_START_HERE.md"
rm -f API_DOCUMENTATION.md && ((files_removed++)) && echo "✓ Removed API_DOCUMENTATION.md"
rm -f API_REFERENCE.md && ((files_removed++)) && echo "✓ Removed API_REFERENCE.md"
rm -f API_TESTING.md && ((files_removed++)) && echo "✓ Removed API_TESTING.md"
rm -f API_VERIFICATION_REPORT.md && ((files_removed++)) && echo "✓ Removed API_VERIFICATION_REPORT.md"
rm -f ARCHITECTURE.md && ((files_removed++)) && echo "✓ Removed ARCHITECTURE.md"
rm -f COMPLETE_CHECKLIST.md && ((files_removed++)) && echo "✓ Removed COMPLETE_CHECKLIST.md"
rm -f COMPLETION_REPORT.md && ((files_removed++)) && echo "✓ Removed COMPLETION_REPORT.md"
rm -f CONTRIBUTING.md && ((files_removed++)) && echo "✓ Removed CONTRIBUTING.md"
rm -f DEPLOYMENT.md && ((files_removed++)) && echo "✓ Removed DEPLOYMENT.md"
rm -f DEPLOYMENT_GUIDE.md && ((files_removed++)) && echo "✓ Removed DEPLOYMENT_GUIDE.md"
rm -f DOCUMENTATION_COMPLETE.md && ((files_removed++)) && echo "✓ Removed DOCUMENTATION_COMPLETE.md"
rm -f ERROR_PREVENTION_GUIDE.md && ((files_removed++)) && echo "✓ Removed ERROR_PREVENTION_GUIDE.md"
rm -f EVERYTHING_READY.md && ((files_removed++)) && echo "✓ Removed EVERYTHING_READY.md"
rm -f EXECUTIVE_SUMMARY.md && ((files_removed++)) && echo "✓ Removed EXECUTIVE_SUMMARY.md"
rm -f FILES_CREATED.md && ((files_removed++)) && echo "✓ Removed FILES_CREATED.md"
rm -f FINAL_CHECKLIST.md && ((files_removed++)) && echo "✓ Removed FINAL_CHECKLIST.md"
rm -f FINAL_IMPROVEMENTS.md && ((files_removed++)) && echo "✓ Removed FINAL_IMPROVEMENTS.md"
rm -f FINAL_STATUS.md && ((files_removed++)) && echo "✓ Removed FINAL_STATUS.md"
rm -f FINAL_VERIFICATION.txt && ((files_removed++)) && echo "✓ Removed FINAL_VERIFICATION.txt"
rm -f IMPLEMENTATION_COMPLETE.md && ((files_removed++)) && echo "✓ Removed IMPLEMENTATION_COMPLETE.md"
rm -f IMPLEMENTATION_VERIFICATION.md && ((files_removed++)) && echo "✓ Removed IMPLEMENTATION_VERIFICATION.md"
rm -f INSTALLATION_CHECKLIST.md && ((files_removed++)) && echo "✓ Removed INSTALLATION_CHECKLIST.md"
rm -f LAUNCH_README.md && ((files_removed++)) && echo "✓ Removed LAUNCH_README.md"
rm -f MAIN_DOCUMENTATION_INDEX.md && ((files_removed++)) && echo "✓ Removed MAIN_DOCUMENTATION_INDEX.md"
rm -f MAIN_IMPLEMENTATION_COMPLETE.md && ((files_removed++)) && echo "✓ Removed MAIN_IMPLEMENTATION_COMPLETE.md"
rm -f MAIN_JS_README.md && ((files_removed++)) && echo "✓ Removed MAIN_JS_README.md"
rm -f MAIN_LAUNCHER_GUIDE.md && ((files_removed++)) && echo "✓ Removed MAIN_LAUNCHER_GUIDE.md"
rm -f NEXT_STEPS.md && ((files_removed++)) && echo "✓ Removed NEXT_STEPS.md"
rm -f PRODUCTION_MASTER_GUIDE.md && ((files_removed++)) && echo "✓ Removed PRODUCTION_MASTER_GUIDE.md"
rm -f PRODUCTION_READY_SUMMARY.md && ((files_removed++)) && echo "✓ Removed PRODUCTION_READY_SUMMARY.md"
rm -f PROJECT_COMPLETION.md && ((files_removed++)) && echo "✓ Removed PROJECT_COMPLETION.md"
rm -f QUICK_LAUNCH_CHECKLIST.md && ((files_removed++)) && echo "✓ Removed QUICK_LAUNCH_CHECKLIST.md"
rm -f QUICK_REFERENCE.md && ((files_removed++)) && echo "✓ Removed QUICK_REFERENCE.md"
rm -f QUICK_RUN.md && ((files_removed++)) && echo "✓ Removed QUICK_RUN.md"
rm -f QUICK_START.md && ((files_removed++)) && echo "✓ Removed QUICK_START.md"
rm -f README_NEW.md && ((files_removed++)) && echo "✓ Removed README_NEW.md"
rm -f RESOLUTION_SUMMARY.md && ((files_removed++)) && echo "✓ Removed RESOLUTION_SUMMARY.md"
rm -f START_HERE_NOW.md && ((files_removed++)) && echo "✓ Removed START_HERE_NOW.md"
rm -f START_WITH_MAIN_JS.md && ((files_removed++)) && echo "✓ Removed START_WITH_MAIN_JS.md"
rm -f SUMMARY.md && ((files_removed++)) && echo "✓ Removed SUMMARY.md"
rm -f TESTING.md && ((files_removed++)) && echo "✓ Removed TESTING.md"
rm -f TRANSFORMATION_COMPLETE.md && ((files_removed++)) && echo "✓ Removed TRANSFORMATION_COMPLETE.md"
rm -f VISUAL_SUMMARY.md && ((files_removed++)) && echo "✓ Removed VISUAL_SUMMARY.md"
rm -f final-check.sh && ((files_removed++)) && echo "✓ Removed final-check.sh"
rm -f quick-launch.sh && ((files_removed++)) && echo "✓ Removed quick-launch.sh"
rm -f setup-quick.sh && ((files_removed++)) && echo "✓ Removed setup-quick.sh"
rm -f setup.sh && ((files_removed++)) && echo "✓ Removed setup.sh"
rm -f start.sh && ((files_removed++)) && echo "✓ Removed start.sh"
rm -f validate.sh && ((files_removed++)) && echo "✓ Removed validate.sh"
rm -f launch.sh && ((files_removed++)) && echo "✓ Removed launch.sh"
rm -f cleanup.sh && ((files_removed++)) && echo "✓ Removed cleanup.sh"
rm -f cleanup_files.py && ((files_removed++)) && echo "✓ Removed cleanup_files.py"

echo ""
echo "========================================="
echo "✓ Cleanup complete! Removed $files_removed files"
echo "========================================="
echo ""
echo "Essential files remaining:"
echo "  - main.js (launcher)"
echo "  - package.json (dependencies)"
echo "  - docker-compose.yml (Docker setup)"
echo "  - README.md (main docs)"
echo "  - LAUNCH_INSTRUCTIONS.md"
echo "  - STARTUP_GUIDE.md"
echo "  - COMPREHENSIVE_SETUP.md"
echo "  - QUICK_REFERENCE.txt"
echo "  - PROJECT_COMPLETE.md"
echo "  - IMPLEMENTATION_SUMMARY.md"
echo "  - DOCUMENTATION_INDEX.md"
echo "  - error-recovery.js"
echo "  - verify-startup.js"
echo "  - pre-launch-check.js"
echo "  - /backend/ (application)"
echo "  - /frontend/ (application)"
